version: "3"

services:
  user:
    image: "dislinkt:user"
    build:
      context: "./microservices/user"
    expose:
      - "50051"
    depends_on:
      - "neo"
    networks:
      - neo4j_net
      - microservices
    environment:
      NODE_ENV: "test"
      URL: "0.0.0.0"
      PORT: "50051"
      NEO4J_SCHEME: "bolt"
      NEO4J_HOST: "neo"
      NEO4J_PORT: "7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "neo"
    restart: "on-failure"

  auth:
    image: "dislinkt:auth"
    build:
      context: "./microservices/auth"
    expose:
      - "50052"
    depends_on:
      - "neo"
    networks:
      - neo4j_net
      - microservices
    environment:
      NODE_ENV: "test"
      URL: "0.0.0.0"
      PORT: "50052"
      USER_SERVICE_URL: "user"
      USER_SERVICE_PORT: "50051"
    restart: "on-failure"

  api-gateway:
    image: "api-gateway:dev"
    build:
      context: "./api-gateway"
    ports:
      - "3000:3000"
    networks:
      - microservices
    depends_on:
      - "user"
    environment:
      NODE_ENV: "test"
      PORT: "3000"
      USER_SERVICE_URL: "user"
      USER_SERVICE_PORT: "50051"
      AUTH_SERVICE_URL: "auth"
      AUTH_SERVICE_PORT: "50052"
    restart: "on-failure"

  neo:
    image: neo4j:latest
    ports: 
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data/
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/neo
      # - NEO4JLABS_PLUGINS=["apoc"]
    networks:
      - neo4j_net
    restart: "on-failure"
      

volumes:
  neo4j_data:

networks:
  microservices:
  neo4j_net:
    driver: bridge
